### PR TITLE
SOLR refactoring

### PR DESCRIPTION
**Pull request by enicolasgomez**

### CODE REVIEW

**Comment by enicolasgomez** [comment]
@jrmartin the most interesting part is :

https://github.com/MetaCell/virtual-fly-brain/blob/feature/49-50-sync-solr-refactor/applications/virtual-fly-brain/client/src/shared/subHeader/SearchBuilder.js#L228

specifically the handleResults which should update the search builder component

**Comment by jrmartin** [comment]
@enicolasgomez How are you testing that the circuit browser and term context work?

I only see stack viewer , term info and canvas 
image

**Review by ddelpiano — CHANGES_REQUESTED** [review]
I can see from the refactoring that we are not preserving entirely the previous functionalities.
Here we are not just refactoring the client but we are also unifing the configuration for datasource and search configuration, please be aware that different components have different filters/behaviour in the search, look at:
https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/components/configuration/VFBCircuitBrowser/datasources/SOLRclient.tsx
https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/components/configuration/VFBMain/searchConfiguration.js
https://github.com/VirtualFlyBrain/geppetto-vfb/blob/9e0a4b73a60113b50d4ae9babd59ba553934f40c/components/configuration/VFBMain/queryBuilderConfiguration.js#L375

We need to support these customisations done, the refactoring should aim to get a single client instance that accepts different datasources and configurations (based on the component that invoke it) rather than oversimplyfing the search.

Except the comment above, overall it's a good job and it cleans a lot the current implementation.

thanks!

**Comment by enicolasgomez** [comment]
@ddelpiano will need more details as I'm not quite following your last comments, here's why:

- there's no client instance as it's a singe abstract function getResultsSOLR acting as entry point which accepts searchString, return formatter, sorter and configuration

- all the existing configurations has been ported out from the old code based and are being used in the components and passed to the get results function

https://github.com/MetaCell/virtual-fly-brain/blob/feature/49-50-sync-solr-refactor-fixes/applications/virtual-fly-brain/client/src/shared/subHeader/SearchBuilder.js#L221

https://github.com/MetaCell/virtual-fly-brain/blob/feature/49-50-sync-solr-refactor-fixes/applications/virtual-fly-brain/client/src/shared/subHeader/SearchBuilder.js#L228C7-L228C21

so maybe what you are saying is we should transform this to a helper object that would handle all this configurations internally so the clients don't need to setup the function theyselves?

**Review by jrmartin — CHANGES_REQUESTED** [review]
I tested this locally, and can see the Circuit Browser working fine, I don't see the VFBGraph working at all though. 

For the Circuit Browser there's some styling issues, not sure if it was part of the scope of this PR to apply same style as before. cc @ddelpiano 
- Font inside nodes is deformed
image

- The empty component text is hard to read. Again, not sure if it was part of the scope of this card to apply styling. 
image

The VFBGraph is empty, and not responsive.
image

**Comment by enicolasgomez** [comment]
@ddelpiano @jrmartin closing this one as has been addressed by:
https://github.com/MetaCell/virtual-fly-brain/pull/60

**Pull request closed without merging**
